#_______________________Pmake___________________________________________________
#
#	Makefile : 	Tut plugin
# 	Mar 2007	Bert Bril
#	RCS:		$Id: Makefile,v 1.5 2007-06-19 10:01:43 cvsraman Exp $
#_______________________________________________________________________________


SRC.cc := uiqvelseistools.cc \
	  uiqvelhortools.cc \
	  uiqvelattrib.cc \
	  uiqvelwelltools.cc \
	  uiqvelpi.cc

PLUGIN := yes
PLUGINDEP := QVel
MODDEP := uiODMain
REFERS_QTLIBS := yes

include make.od.Defaults
include make.Targets
